[project]
name = "crawler"
version = "0.1.0"
description = "Search for and rescue life support pods after failed launch from planet surface"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "pytmx>=3.32",
]
